export const CHANGE_INPUT_VALUE = 'change_input_value'
export const ADD_LIST = 'add_list'
export const DEL_ITEM  = 'del_item'
export const INIT_LIST = 'init_list'
export const getAllList ='getAllList'
